# Generated by Django 4.2.4 on 2023-09-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pruebas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='pfp.png', upload_to='images/'),
        ),
    ]
